# Generated by Django 6.0.3 on 2026-04-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('JazzCash', 'JazzCash'), ('EasyPaisa', 'EasyPaisa'), ('Bank', 'Bank Transfer')], default='COD', max_length=20),
        ),
    ]
